### ISSUE TITLE
error on model with sequence types/layers

### ISSUE THREAD

**Issue by bas-aarts** [onnx/optimizer#134]
when running
`python -m onnxoptimizer input.onnx out
`
on the attached .onnx file. I get
```
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.8/3.8.16/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/homebrew/Cellar/python@3.8/3.8.16/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/bas/src/tetra/tetra-dev/lib/python3.8/site-packages/onnxoptimizer/__main__.py", line 15, in <module>
    main()
[input.onnx.zip](https://github.com/onnx/optimizer/files/11379347/input.onnx.zip)

  File "/Users/bas/src/tetra/tetra-dev/lib/python3.8/site-packages/onnxoptimizer/onnxoptimizer_main.py", line 84, in main
    onnx.checker.check_model(output_file)
  File "/Users/bas/src/tetra/tetra-dev/lib/python3.8/site-packages/onnx/checker.py", line 108, in check_model
    C.check_model_path(model, full_check)
onnx.onnx_cpp2py_export.checker.ValidationError: Field 'type' of 'value_info' is required but missing.

```
this is with onnxoptimizer==0.3.13

**Comment by bas-aarts** [comment]
this happens on all models with a SequenceConstruct layer

**Comment by take-cheeze** [comment]
It's reproducable on models with sequence type outputs like following: `python -m onnxoptimizer third_party/onnx/onnx/backend/test/data/node/test_sequence_insert_at_back/model.onnx out`
The main cause is incomplete sequence type support in current ir: https://github.com/onnx/onnx/blob/ef139f445e1ab5110779cd0b2785bd697a6f845f/onnx/common/ir_pb_converter.cc#L611-L615
Running shape inference like follwing may mitigate the problem:

```diff
modified   onnxoptimizer/onnxoptimizer_main.py
@@ -59,6 +59,12 @@ def main():
     parser.add_argument(
         "--fixed_point", action="store_true", default=False, help="fixed point"
     )
+    parser.add_argument(
+        "--skip_infer_shapes",
+        action="store_true",
+        default=False,
+        help="Skip shape inference after optimization",
+    )
     argv = sys.argv.copy()
     args = parser.parse_args(format_argv(sys.argv))
 
@@ -98,6 +104,8 @@ def main():
     if model is None:
         print("onnxoptimizer failed")
         sys.exit(1)
+    if not args.skip_infer_shapes:
+        model = onnx.shape_inference.infer_shapes(model)
     try:
         onnx.save(proto=model, f=output_file)
     except Exception:

```
